ION SDP Unmapped heap driver.
This is ION driver with unmapped heap patches from SWG
taken from HiKey v4.9 kernel, and back ported onto v4.4.

With this driver, and optee 2.6.0 I have xtest --sdp-basic
working on X15 HS board.

The following commits need to be reverted in optee-test
(which align ION API with v4.12 kernel which doesn't
compile well on v4.4 kernel).

optee_test
git revert cc72dd2ce5c45318ad1618633bf0c859ad56cd8a
git revert 3a34b981af16dcecb4bb5c4648a95beefe1a22c5
git revert 8bc3142b3b2b7cb5dfbbdca714d334dfdcf5454c

am57xevm:/ # xtest --sdp-basic

Secure Data Path basic access: NS invokes SDP TA
Allocate in ION heap 'unmapped'
Test passed

Secure Data Path basic access: SDP TA invokes SDP TA
Allocate in ION heap 'unmapped'
Test passed

Secure Data Path basic access: SDP TA invokes SDP pTA
Allocate in ION heap 'unmapped'
Test passed

Secure Data Path basic access: NS invokes SDP pTA (shall fail)
Allocate in ION heap 'unmapped'
Error: invoke SDP test TA (inject) failed ffff0006 3

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>